stages:
  - build
  - test
  - ui-test

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - gem install bundler

build:
  stage: build
  script:
    - fastlane build
  tags:
    - android

test:
  stage: test
  script:
    - fastlane tests
  tags:
    - android

ui-test:
  stage: ui-test
  script:
    - fastlane ui_tests
  tags:
    - android